version: '2'

services:
 web:
  build: .
  volumes:
    - .:/usr/src/app
  expose:
    - "${LOCAL_PORT}"
  ports:
    - ${LOCAL_PORT}:${LOCAL_PORT}
  environment:
    LOCAL_PORT: ${LOCAL_PORT}
  command: ./start.sh

